### ISSUE TITLE
Re: Payment action: PURCHASE

### ISSUE THREAD

**Issue by KramarzGIT** [BOIPA/WooCommerce_plugin#2]
Hi guys,

An option to decide weather to change the Order Status to Completed or not is needed, when using Payment action: PURCHASE.

Like it is available with plugin you have recommended so far from customweb guys.

Without it orders are marked as completed straight away and customers gets emails about orders getting despatched while they are not.

Any chance for that addition?

Regards
Michal

**Comment by kieranmurray** [comment]
Hi Michal,

Thanks for your message. I will relay this to the developers for their feedback.

Thanks,
Kieran
