### ISSUE TITLE
Re: Payment action: AUTH

### ISSUE THREAD

**Issue by KramarzGIT** [BOIPA/WooCommerce_plugin#3]
When the above option is chosen, orders are marked as COMPLETED website side.

Shouldn't that be ON HOLD instead? There's no way to capture them when they are COMPLETED straight away?

Confused...

**Comment by kieranmurray** [comment]
Thanks for your message.

When you say "website side" do you mean the Order section of WooCommerce, or somewhere else?
I tested and the Status correctly shows as "On Hold" until i capture or void it.

Can you go back to the plugin settings page and verify that the payment action is indeed set to AUTH?
if it is, please send me a screenshot of the response along with your merchant ID and WooCommerce version and I will investigate.

Thanks,
Kieran Murray
Intelligent Payments

**Comment by KramarzGIT** [comment]
Hi Kieran,

Yes, I meant Order Section.

Merchant ID: 100105
WooCommerce Version: 3.9.2

Not sure what you mean by ‘response’.

The log says this for example:
[...] DIDNT KNOW IT WILL BE PUBLISHED HERE... REMOVED

Kind Regards
Michal

**Comment by KramarzGIT** [comment]
Also how do we actually “capture” the payment.  In Turnkey, it says “set for capture”.  How do we actually capture it?

Regards
Elaine

**Comment by kieranmurray** [comment]
If the payment action is set to "AUTH" in the plugin settings, the status will be "not set for capture" so please verify that you are settings this and saving it afterwards.
To capture a transaction via the WooCommerce plugin, please follow the instruction on the Wiki page. https://github.com/BOIPA/WooCommerce_plugin/wiki/Installation-of-BOIPA-Plugin-for-WooCommerce

**Comment by KramarzGIT** [comment]
It is set to AUTH - saved multiple times.

When it was set to PURCHASE, log was showing "status":"CAPTURED" for orders.

With AUTH, log shows "status":"SET_FOR_CAPTURE" for orders.

We can't capture transactions via plugin as orders are marked as completed = no 'Capture Online' option available.

Client doesn't even know how to capture those orders through Turkney at this stage...

**Comment by KramarzGIT** [comment]
Here's a cut from a log string that shows AUTH active:

"acquirerCurrency":"GBP","action":"AUTH","paymentSolutionId":"500","currency":"GBP","pan":"8513564666928281","status":"SET_FOR_CAPTURE","originalTxId":"null"
